name = "father-memorial-api"
main = "src/index.js"
compatibility_date = "2026-05-04"
workers_dev = false
preview_urls = false
routes = [
    { pattern = "api.mingfu.ccwu.cc", custom_domain = true }
]

[[d1_databases]]
binding = "DB"
database_name = "father_memorial"
database_id = "70aa3f94-0c06-44d3-93b2-3cab7b1ba8ad"
